const fs = require('fs');
let code = fs.readFileSync('src/App.tsx', 'utf-8');

const targetStrEx = `                    ) : selectedLesson.id === "l20" && activeSubTab === "exercises" ? (<Lektion20VocabEx playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l21" && activeSubTab === "exercises" ? (<Lektion21VocabEx playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l22" && activeSubTab === "exercises" ? (<Lektion22VocabEx playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l23" && activeSubTab === "exercises" ? (<Lektion23VocabEx playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l24" && activeSubTab === "exercises" ? (<Lektion24VocabEx playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l21" && activeSubTab === "exercises" ? (<Lektion21VocabEx playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l22" && activeSubTab === "exercises" ? (<Lektion22VocabEx playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l23" && activeSubTab === "exercises" ? (<Lektion23VocabEx playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l24" && activeSubTab === "exercises" ? (<Lektion24VocabEx playAudio={playAudio} playingId={playingId} />`;

const replacedStrEx = `                    ) : selectedLesson.id === "l20" && activeSubTab === "exercises" ? (<Lektion20VocabEx playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l21" && activeSubTab === "exercises" ? (<Lektion21VocabEx playAudio={playAudio} playingId={playingId} />)`;

code = code.replace(targetStrEx, replacedStrEx);

const targetStrTh = `                    ) : selectedLesson.id === "l20" && activeSubTab === "theory" ? (<Lektion20VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l21" && activeSubTab === "theory" ? (<Lektion21VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l22" && activeSubTab === "theory" ? (<Lektion22VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l23" && activeSubTab === "theory" ? (<Lektion23VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l24" && activeSubTab === "theory" ? (<Lektion24VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l21" && activeSubTab === "theory" ? (<Lektion21VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l22" && activeSubTab === "theory" ? (<Lektion22VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l23" && activeSubTab === "theory" ? (<Lektion23VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l24" && activeSubTab === "theory" ? (<Lektion24VocabTheory playAudio={playAudio} playingId={playingId} />`;

const replacedStrTh = `                    ) : selectedLesson.id === "l20" && activeSubTab === "theory" ? (<Lektion20VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l21" && activeSubTab === "theory" ? (<Lektion21VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l22" && activeSubTab === "theory" ? (<Lektion22VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l23" && activeSubTab === "theory" ? (<Lektion23VocabTheory playAudio={playAudio} playingId={playingId} />) : selectedLesson.id === "l24" && activeSubTab === "theory" ? (<Lektion24VocabTheory playAudio={playAudio} playingId={playingId} />)`;

code = code.replace(targetStrTh, replacedStrTh);

fs.writeFileSync('src/App.tsx', code);
console.log('Cleaned redundancies.');
