const fs = require('fs');
const docx = require('docx');
const { Document, Packer, Paragraph, TextRun, HeadingLevel } = docx;

const doc = new Document({
  sections: [{
    children: [
      new Paragraph({ text: "Tổng hợp Từ Vựng Tiếng Đức B1", heading: HeadingLevel.TITLE }),
      
      new Paragraph({ text: "Lektion 15: Truyền thông & Đời sống số", heading: HeadingLevel.HEADING_1 }),
      new Paragraph("der Sender: Kênh truyền hình"),
      new Paragraph("die Sendung: Chương trình truyền hình/phát sóng"),
      new Paragraph("das Programm: Chương trình truyền hình"),
      new Paragraph("der Rundfunk: Đài phát thanh"),
      new Paragraph("die Folge: Tập phim"),
      new Paragraph("produzieren: Sản xuất"),
      new Paragraph("der Bildschirm: Màn hình"),
      new Paragraph("die Tastatur: Bàn phím"),
      new Paragraph("das Kabel: Dây cáp"),
      new Paragraph("der Stecker: Giắc cắm"),
      new Paragraph("die Maus: Con chuột máy tính"),
      new Paragraph("der Monitor: Màn hình hiển thị"),
      new Paragraph("abstürzen: Bị treo, sập (máy tính)"),
      new Paragraph("speichern: Lưu trữ"),
      new Paragraph("löschen: Xóa bỏ"),
      new Paragraph("tippen: Đánh máy"),
      new Paragraph("das Passwort: Mật khẩu"),
      new Paragraph("das Laufwerk: Ổ đĩa"),

      new Paragraph({ text: "Lektion 16: Dịch vụ & Khách sạn", heading: HeadingLevel.HEADING_1 }),
      new Paragraph("das Einzelzimmer: Phòng đơn"),
      new Paragraph("das Doppelzimmer: Phòng đôi"),
      new Paragraph("die Halbpension: Bao 2 bữa (sáng + tối)"),
      new Paragraph("die Vollpension: Bao 3 bữa"),
      new Paragraph("das WLAN: Wi-Fi phủ sóng"),
      new Paragraph("die Rezeption: Quầy Lễ tân"),
      new Paragraph("die Reservierung: Sự đặt phòng"),
      new Paragraph("der Schlüssel: Chìa khóa phòng"),
      new Paragraph("das Gepäck: Hành lý"),
      new Paragraph("der Aufzug: Thang máy"),
      new Paragraph("das Zimmermädchen: Cô kỹ thuật viên / hầu phòng"),
      new Paragraph("der Portier: Người khuân vác, gác cửa khách sạn"),
      new Paragraph("ausgebucht: Hết phòng, kín chỗ"),
      new Paragraph("das Trinkgeld: Tiền boa/tiền thưởng"),

      new Paragraph({ text: "Lektion 17: Du lịch & Khám phá", heading: HeadingLevel.HEADING_1 }),
      new Paragraph("die Tankstelle: Trạm xăng"),
      new Paragraph("die Ampel: Đèn giao thông"),
      new Paragraph("die Autobahn: Đường cao tốc"),
      new Paragraph("die Grenze: Biên giới"),
      new Paragraph("die Fähre: Phà qua sông/biển"),
      new Paragraph("die Panne: Sự cố, hỏng xe trên đường"),
      new Paragraph("der Reifen: Lốp xe ô tô"),
      new Paragraph("die Abfahrt: Sự khởi hành"),
      new Paragraph("die Ankunft: Sự đến nơi"),
      new Paragraph("das Meer / die See: Biển"),
      new Paragraph("die Küste: Bờ biển"),
      new Paragraph("der Strand: Bãi biển"),
      new Paragraph("die Insel: Hòn đảo"),
      new Paragraph("die Berge / das Gebirge: Núi / Dãy núi"),
      new Paragraph("der Wald: Rừng cây"),
      new Paragraph("die Wüste: Sa mạc"),
      new Paragraph("das Zelt: Bạt / Cái lều"),
      new Paragraph("sich ausruhen: Nghỉ ngơi"),
      new Paragraph("einschlafen: Ngủ thiếp đi"),
      new Paragraph("erleben: Trải nghiệm"),
      new Paragraph("der Reiseführer: Hướng dẫn viên / sách hướng dẫn"),
      new Paragraph("die Sehenswürdigkeit: Danh lam thắng cảnh"),
      new Paragraph("das Denkmal: Đài kỷ niệm"),
      new Paragraph("die Führung: Chuyến đi tham quan có hướng dẫn"),

      new Paragraph({ text: "Lektion 18: Giao thông, Thời tiết & Phương hướng", heading: HeadingLevel.HEADING_1 }),
      new Paragraph("die Sonne: Mặt trời"),
      new Paragraph("der Regen: Mưa"),
      new Paragraph("der Schnee: Tuyết"),
      new Paragraph("der Wind: Gió"),
      new Paragraph("der Nebel: Sương mù"),
      new Paragraph("das Gewitter: Dông bão"),
      new Paragraph("die Hitze: Sự nóng bức"),
      new Paragraph("die Kälte: Sự lạnh lẽo"),
      new Paragraph("warm: Ấm áp"),
      new Paragraph("bewölkt: Nhiều mây"),
      new Paragraph("das Handtuch: Khăn tắm"),
      new Paragraph("die Badehose: Quần bơi nam"),
      new Paragraph("die Sonnencreme: Kem chống nắng"),
      new Paragraph("der Golfplatz: Sân chơi golf"),
      new Paragraph("der Parkplatz: Bãi đỗ xe"),
      new Paragraph("das Freizeitland: Khu vui chơi, công viên giải trí"),
      new Paragraph("geradeaus: Đi thẳng"),
      new Paragraph("links / rechts: Bên trái / Bên phải"),
      new Paragraph("dahinter: Phía sau đó"),
      new Paragraph("vorbei: Đi ngang qua"),
      new Paragraph("die Kreuzung: Ngã tư"),

      new Paragraph({ text: "Lektion 21: Nơi làm việc & Công sở", heading: HeadingLevel.HEADING_1 }),
      new Paragraph("der Arbeitgeber: Nhà tuyển dụng"),
      new Paragraph("der Arbeitnehmer: Người lao động"),
      new Paragraph("der Kollege / die Kollegin: Đồng nghiệp"),
      new Paragraph("die Besprechung / das Meeting: Cuộc họp"),
      new Paragraph("das Gehalt / der Lohn: Mức lương chi trả"),
      new Paragraph("kündigen: Sa thải / Xin nghỉ việc"),
      new Paragraph("der Betriebsrat: Công đoàn cơ sở"),
      new Paragraph("die Abteilung: Phòng ban / Bộ phận trong công ty"),
      new Paragraph("der Feierabend: Giờ tan làm / Quãng thời gian sau giờ làm"),
      new Paragraph("die Überstunde: Giờ làm thêm"),

      new Paragraph({ text: "Lektion 22: Nghề nghiệp & Khởi nghiệp", heading: HeadingLevel.HEADING_1 }),
      new Paragraph("die Chipkarte: Thẻ chip"),
      new Paragraph("der Vertrag: Hợp đồng (Lao động/Thuê nhà)"),
      new Paragraph("anmelden: Đăng ký / Báo danh"),
      new Paragraph("mieten: Thuê mướn"),
      new Paragraph("teilen: Chia sẻ"),
      new Paragraph("umweltfreundlich: Thân thiện với môi trường"),
      new Paragraph("die Bewerbung: Đơn xin việc"),
      new Paragraph("der Lebenslauf: Sơ yếu lý lịch (CV)"),
      new Paragraph("das Vorstellungsgespräch: Cuộc phỏng vấn xin việc"),
      new Paragraph("die Berufserfahrung: Kinh nghiệm làm việc chuyên môn"),
      new Paragraph("einstellen: Tuyển dụng, nhận ai đó vào làm"),
      new Paragraph("die Qualifikation: Bằng cấp / Trình độ chuyên môn"),
      new Paragraph("die Vollzeit / Teilzeit: Làm toàn thời gian / Làm bán thời gian"),

      new Paragraph({ text: "Lektion 23: Học tập & Xã hội Đức", heading: HeadingLevel.HEADING_1 }),
      new Paragraph("die Grundschule: Trường tiểu học"),
      new Paragraph("die Realschule: Trường thực hành"),
      new Paragraph("das Gymnasium: Trường trung học chuyên"),
      new Paragraph("das Abitur: Bằng tốt nghiệp tú tài / phổ thông"),
      new Paragraph("die Lehre / Ausbildung: Quá trình học nghề"),
      new Paragraph("das Studium: Việc học đại học / bậc đại học"),
      new Paragraph("die Demokratie: Nền Dân chủ"),
      new Paragraph("das Gesetz: Đạo luật / Pháp luật"),
      new Paragraph("wählen: Lựa chọn / Bầu cử"),
      new Paragraph("die Regierung: Chính phủ"),
      new Paragraph("die Partei: Đảng phái chính trị"),

      new Paragraph({ text: "Lektion 24: Đánh giá & Chứng chỉ", heading: HeadingLevel.HEADING_1 }),
      new Paragraph("schriftlich: (Dưới dạng) bằng văn bản, thi viết"),
      new Paragraph("mündlich: (Dưới dạng) bằng miệng, thi nói"),
      new Paragraph("das Zeugnis: Giấy chứng nhận, học bạ điểm"),
      new Paragraph("die Prüfung: Bài thi, Kỳ thi"),
      new Paragraph("bestehen: Thi đỗ, Vượt qua kỳ thi"),
      new Paragraph("durchfallen: Thi rớt, thi trượt"),
      new Paragraph("die Note: Điểm số"),
      new Paragraph("das Zertifikat: Bằng cấp, chứng chỉ ngôn ngữ"),
      new Paragraph("korrigieren: Sửa chữa, chấm bài (của giáo viên)"),
      new Paragraph("der Fehler: Lỗi sai"),
    ]
  }]
});

Packer.toBuffer(doc).then((buffer) => {
  fs.writeFileSync('./public/Tu_Vung_Tieng_Duc_Tong_Hop.docx', buffer);
  console.log("Done");
});
